/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeesIndexImport } from './routes/employees/index'
import { Route as CafesIndexImport } from './routes/cafes/index'
import { Route as EmployeesEditImport } from './routes/employees/edit'
import { Route as EmployeesCreateImport } from './routes/employees/create'
import { Route as CafesEditImport } from './routes/cafes/edit'
import { Route as CafesCreateImport } from './routes/cafes/create'

// Create/Update Routes

const EmployeesIndexRoute = EmployeesIndexImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRoute,
} as any)

const CafesIndexRoute = CafesIndexImport.update({
  id: '/cafes/',
  path: '/cafes/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeesEditRoute = EmployeesEditImport.update({
  id: '/employees/edit',
  path: '/employees/edit',
  getParentRoute: () => rootRoute,
} as any)

const EmployeesCreateRoute = EmployeesCreateImport.update({
  id: '/employees/create',
  path: '/employees/create',
  getParentRoute: () => rootRoute,
} as any)

const CafesEditRoute = CafesEditImport.update({
  id: '/cafes/edit',
  path: '/cafes/edit',
  getParentRoute: () => rootRoute,
} as any)

const CafesCreateRoute = CafesCreateImport.update({
  id: '/cafes/create',
  path: '/cafes/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cafes/create': {
      id: '/cafes/create'
      path: '/cafes/create'
      fullPath: '/cafes/create'
      preLoaderRoute: typeof CafesCreateImport
      parentRoute: typeof rootRoute
    }
    '/cafes/edit': {
      id: '/cafes/edit'
      path: '/cafes/edit'
      fullPath: '/cafes/edit'
      preLoaderRoute: typeof CafesEditImport
      parentRoute: typeof rootRoute
    }
    '/employees/create': {
      id: '/employees/create'
      path: '/employees/create'
      fullPath: '/employees/create'
      preLoaderRoute: typeof EmployeesCreateImport
      parentRoute: typeof rootRoute
    }
    '/employees/edit': {
      id: '/employees/edit'
      path: '/employees/edit'
      fullPath: '/employees/edit'
      preLoaderRoute: typeof EmployeesEditImport
      parentRoute: typeof rootRoute
    }
    '/cafes/': {
      id: '/cafes/'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesIndexImport
      parentRoute: typeof rootRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/cafes/create': typeof CafesCreateRoute
  '/cafes/edit': typeof CafesEditRoute
  '/employees/create': typeof EmployeesCreateRoute
  '/employees/edit': typeof EmployeesEditRoute
  '/cafes': typeof CafesIndexRoute
  '/employees': typeof EmployeesIndexRoute
}

export interface FileRoutesByTo {
  '/cafes/create': typeof CafesCreateRoute
  '/cafes/edit': typeof CafesEditRoute
  '/employees/create': typeof EmployeesCreateRoute
  '/employees/edit': typeof EmployeesEditRoute
  '/cafes': typeof CafesIndexRoute
  '/employees': typeof EmployeesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/cafes/create': typeof CafesCreateRoute
  '/cafes/edit': typeof CafesEditRoute
  '/employees/create': typeof EmployeesCreateRoute
  '/employees/edit': typeof EmployeesEditRoute
  '/cafes/': typeof CafesIndexRoute
  '/employees/': typeof EmployeesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cafes/create'
    | '/cafes/edit'
    | '/employees/create'
    | '/employees/edit'
    | '/cafes'
    | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cafes/create'
    | '/cafes/edit'
    | '/employees/create'
    | '/employees/edit'
    | '/cafes'
    | '/employees'
  id:
    | '__root__'
    | '/cafes/create'
    | '/cafes/edit'
    | '/employees/create'
    | '/employees/edit'
    | '/cafes/'
    | '/employees/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CafesCreateRoute: typeof CafesCreateRoute
  CafesEditRoute: typeof CafesEditRoute
  EmployeesCreateRoute: typeof EmployeesCreateRoute
  EmployeesEditRoute: typeof EmployeesEditRoute
  CafesIndexRoute: typeof CafesIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  CafesCreateRoute: CafesCreateRoute,
  CafesEditRoute: CafesEditRoute,
  EmployeesCreateRoute: EmployeesCreateRoute,
  EmployeesEditRoute: EmployeesEditRoute,
  CafesIndexRoute: CafesIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/cafes/create",
        "/cafes/edit",
        "/employees/create",
        "/employees/edit",
        "/cafes/",
        "/employees/"
      ]
    },
    "/cafes/create": {
      "filePath": "cafes/create.tsx"
    },
    "/cafes/edit": {
      "filePath": "cafes/edit.tsx"
    },
    "/employees/create": {
      "filePath": "employees/create.tsx"
    },
    "/employees/edit": {
      "filePath": "employees/edit.tsx"
    },
    "/cafes/": {
      "filePath": "cafes/index.tsx"
    },
    "/employees/": {
      "filePath": "employees/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
