/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const EmployeesLazyImport = createFileRoute('/employees')()
const CafesLazyImport = createFileRoute('/cafes')()

// Create/Update Routes

const EmployeesLazyRoute = EmployeesLazyImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/employees.lazy').then((d) => d.Route))

const CafesLazyRoute = CafesLazyImport.update({
  id: '/cafes',
  path: '/cafes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cafes.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesLazyImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/cafes': typeof CafesLazyRoute
  '/employees': typeof EmployeesLazyRoute
}

export interface FileRoutesByTo {
  '/cafes': typeof CafesLazyRoute
  '/employees': typeof EmployeesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/cafes': typeof CafesLazyRoute
  '/employees': typeof EmployeesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cafes' | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to: '/cafes' | '/employees'
  id: '__root__' | '/cafes' | '/employees'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CafesLazyRoute: typeof CafesLazyRoute
  EmployeesLazyRoute: typeof EmployeesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  CafesLazyRoute: CafesLazyRoute,
  EmployeesLazyRoute: EmployeesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/cafes",
        "/employees"
      ]
    },
    "/cafes": {
      "filePath": "cafes.lazy.tsx"
    },
    "/employees": {
      "filePath": "employees.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
